sudo: required
language: generic

services:
  - docker
  
before_install:
  - docker build -t bhadrarahul/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true bhadrarahul/react-test npm test
  
after_success:
  - docker build -t bhadrarahul/multi-client ./client
  - docker build -t bhadrarahul/multi-nginx ./nginx
  - docker build -t bhadrarahul/multi-server ./server
  - docker build -t bhadrarahul/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push bhadrarahul/multi-client
  - docker push bhadrarahul/multi-nginx
  - docker push bhadrarahul/multi-server
  - docker push bhadrarahul/multi-worker
  
deploy:
  provider: elasticbeanstalk
  region: 'us-west-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-west-1-542646078692'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY